import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { json } from "stream/consumers";

const userList: NextPage = () => {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    try {
      const fetchUsers = async () => {
        const response = await fetch("http://localhost:3000/api/users");
        const data = await response.json();
        setUsers(data.users);
      };
      fetchUsers();
    } catch (error) {
      console.log(error);
    }
  }, []);

  return (
    <div>
      <Head>
        <title>User List API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div>{}</div>
          <ul>
            {users.map(({ id, name }) => (
              <li key={id}>{name}</li>
            ))}
          </ul>
        </div>
      </main>
      <footer>footer</footer>
    </div>
  );
};

export default userList;
